channels:
- conda-forge
dependencies:
- python=3.10.13
- pip<=23.3.1
- pip:
  - mlflow==2.10.0
  - cloudpickle==3.0.0
  - imbalanced-learn==0.12.0
  - numpy==1.26.3
  - packaging==23.1
  - pandas==2.2.0
  - psutil==5.9.0
  - pyyaml==6.0.1
  - scikit-learn==1.4.0
  - scipy==1.12.0
  - xgboost==2.0.3
name: mlflow-env
